import scrapy

class PhoneItem(scrapy.Item):
    source_row        = scrapy.Field()
    candidate_index   = scrapy.Field()
    original_cell     = scrapy.Field()
    original_number   = scrapy.Field()
    normalized_number = scrapy.Field()
    csv_CIN           = scrapy.Field()
    csv_CompanyName   = scrapy.Field()
    csv_Emails        = scrapy.Field()
    csv_Website       = scrapy.Field()
    name              = scrapy.Field()
    spam_score        = scrapy.Field()
    spam_type         = scrapy.Field()
    carrier           = scrapy.Field()
    location          = scrapy.Field()
    line_type         = scrapy.Field()
    tags              = scrapy.Field()
    comments_count    = scrapy.Field()
    source_url        = scrapy.Field()
    is_valid_indian   = scrapy.Field()
    validation_status = scrapy.Field()
    validation_reason = scrapy.Field()
    scraped_at        = scrapy.Field()
